Make generated factory request null safe adapters.
rharter/auto-value-moshi pull request #71
Opened 2016-11-06 21:26 UTC by serj-lotutovici

- Introduces nullSafe() element to MoshiAdapterFactory annotation with a
  default value as false (to respect current usages of the library).
- Generated MoshiAdapterFactory will request null safe adapters if
  requested by the user.
- Some minor cleanups (reduced amount of spec and type lookups)

Closes #25 

**Reasoning for extra meta data in the annotation: ** AutoValue by default enforces null safety and users have to explicitly specify that a value is allowed to be null. I reasoned that current users of the library may not expect nulls in their value classes thus such a change could break expected behaviour. This will force users to make a conscious decision wether or not they need their adapters to return null.

2016-11-07 11:15 UTC, serj-lotutovici commented
Btw, while writing this something didn't feel right. The `Processor#process()` method gets all classes annotated with `@MoshiAdapterFactory` and generates the same exact implementation but under the different name. Should we restrict that to only one class?

2016-12-05 15:21 UTC, rharter commented
There was some discussion about how to approach the `@MoshiAdapterFactory` in #40, which covers the challenges of picking one.  Who knows why someone might do that, perhaps they are a large team on a large codebase and a developer doesn't know there is already one there?  I would argue that is a user issue, not something the library should enforce, as there's technically nothing wrong with having multiples.

2016-12-05 15:26 UTC, rharter requested changes

2016-12-05 15:26 UTC, rharter commented on auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiAdapterFactoryProcessor.java
> +  public static final ParameterSpec TYPE_SPEC = ParameterSpec.builder(Type.class, "type").build();
nit: These should be private.

2016-12-13 17:12 UTC, serj-lotutovici commented
@rharter changes done. Travis build failed, but seams because of a network error.

2017-02-06 21:21 UTC, serj-lotutovici commented
@rharter / @hzsweers any thought regarding this one?

2017-02-06 21:24 UTC, rharter approved these changes

2017-02-06 21:25 UTC, rharter commented
Sorry, got lost in thinking it wasn't updated because of (my) red X.  Looks good to me.

2017-02-06 21:25 UTC, merged

2017-02-06 22:44 UTC, hzsweers commented
Not totally sure I agree with this, mostly because it might either be redundant or you forfeit granularity (vs. just tacking on nullsafe() to the adapter you return in the static jsonAdapter() methods. I don't think we'd use it anyway, even if we did want nullsafe on some adapters