Call value method only once if property is nullable.
rharter/auto-value-moshi pull request #81
Opened 2017-02-18 09:16 UTC by serj-lotutovici

Closes #66

2017-02-18 09:22 UTC, ZacSweers approved these changes
lgtm. Let's fix the checkstyle and then we can merge this

2017-02-18 13:57 UTC, rharter approved these changes
Looks great. Thanks!

2017-02-18 19:23 UTC, JakeWharton requested changes

2017-02-18 19:23 UTC, JakeWharton commented on auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java
> +    NameAllocator nameAllocator = new NameAllocator();
You need to add "writer" and "value" to this before the code below runs. Please add a test that uses these two names as properties.

2017-02-18 19:23 UTC, JakeWharton commented on auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java
> +    NameAllocator nameAllocator = new NameAllocator();
Also you either need to add the adapter names or always qualify them with `this.`. Please add a test with two properties, "foo" and "fooAdapter" to ensure this works.

2017-02-20 16:49 UTC, serj-lotutovici commented on auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java
> +    NameAllocator nameAllocator = new NameAllocator();
Done. Decided to go with `this.` when accessing an adapter. 
Pushed as a separate commit for an easier review.

2017-02-20 16:52 UTC, JakeWharton approved these changes

2017-02-20 16:52 UTC, JakeWharton commented on auto-value-moshi/src/test/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtensionTest.java
> +        + "public abstract String aAdapter();\n"
This should be `@Nullable` so that an "aAdapter" local variable is used.

2017-02-20 16:55 UTC, serj-lotutovici commented on auto-value-moshi/src/test/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtensionTest.java
> +        + "public abstract String aAdapter();\n"
oh, what was I thinking)

2017-02-22 16:43 UTC, merged