Added support for package-private jsonAdapter method (#87)
rharter/auto-value-moshi pull request #88
Opened 2017-03-11 19:41 UTC by nedtwigg

2017-03-11 21:00 UTC, grandstaish commented on auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java
> +      if (method.getModifiers().contains(Modifier.STATIC)) {
Minor: you could also check it's non-private here

2017-03-11 21:31 UTC, nedtwigg commented
Seems like the simplest thing to implement, and the easiest thing to
communicate to users, is just "have a static method".

Is there a reason to disallow private static?

On Sat, Mar 11, 2017 at 1:00 PM Bradley Campbell <notifications@github.com>
wrote:

> *@grandstaish* commented on this pull request.
> ------------------------------
>
> In
> auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java
> <https://github.com/rharter/auto-value-moshi/pull/88#discussion_r105542360>
> :
>
> >      TypeElement type = context.autoValueClass();
>      ParameterizedTypeName jsonAdapterType = ParameterizedTypeName.get(
>          ADAPTER_CLASS_NAME, TypeName.get(type.asType()));
>      TypeName returnedJsonAdapter = null;
>      for (ExecutableElement method : ElementFilter.methodsIn(type.getEnclosedElements())) {
> -      if (method.getModifiers().contains(Modifier.STATIC)
> -          && method.getModifiers().contains(Modifier.PUBLIC)) {
> +      if (method.getModifiers().contains(Modifier.STATIC)) {
>
> Minor: you could also check it's non-private here
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rharter/auto-value-moshi/pull/88#pullrequestreview-26431172>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACyhwLsPJQ7304YFFHNLpRbkGwu1OHCpks5rkwtrgaJpZM4MaT48>
> .
>
-- 
Ned Twigg
Lead Software Architect, DiffPlug LLC
540-336-8043 (cell)
888-513-6870 (fax)
340 S Lemon Ave #3433, Walnut, CA 91789

2017-04-09 02:26 UTC, hzsweers commented
> Is there a reason to disallow private static?

I think the point was more that we can't access private methods from the generated factory, so you should only count non-private ones

2017-04-09 02:27 UTC, ZacSweers requested changes

2017-04-09 02:27 UTC, hzsweers commented on auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java
> +      if (method.getModifiers().contains(Modifier.STATIC)) {
Agreed, we need to check this

2017-04-09 18:54 UTC, nedtwigg commented
Fair enough.  Plain-old javac will give the user those warnings, but it's easy to add a little complexity to check it here as well.

2017-04-09 19:01 UTC, hzsweers commented
> in-old javac will give the user those warnings

I think the point is they should be allowed to have a private static method if they want without warnings, and the processor should skip those.

2017-04-09 19:15 UTC, nedtwigg commented
Okey doke :)

2017-04-09 19:20 UTC, hzsweers commented
Just to go last mile here - we could just check the package and make sure it's accessible, and then ignore anything not accessible. That's what we do in RAVE [here](https://github.com/uber-common/rave/blob/master/rave-compiler/src/main/java/com/uber/rave/compiler/RaveProcessor.java#L153-L154)

2017-04-09 19:42 UTC, nedtwigg commented
IMO, the error-checking in this code is harder to read than what the code itself is doing, and it is redundant with what the javac compiler does for free.

Adding a private check was easy, but adding this check is harder enough that my initiative on this minor task is exhausted.  Making our jsonAdapter methods public isn't a huge deal, we'll just continue to workaround in that way.  Feel free to close 👍

2017-04-09 19:45 UTC, hzsweers commented
Its a few more lines and I think a processor should avoid generating invalid code if it can avoid ir. I can just do it in another PR if you don't want to then

2017-04-09 19:45 UTC, closed without merging

2017-04-09 19:47 UTC, hzsweers commented
It also prevents users from intentionally keeping methods exposed to certain packages