Add support for generic types with JsonQualifiers (#92)
rharter/auto-value-moshi pull request #93
Opened 2017-06-28 00:48 UTC by thatJavaNerd

Generated JsonAdapters now supports generic properties that use JsonQualifiers.

I'm kinda new to AutoValue extensions, so please let me know if anything could be written better/more logically!

2017-06-29 09:51 UTC, ZacSweers approved these changes
This looks good to me. Going to see if I can get another set of eyes on this approach before merging. Thanks for the PR!

2017-07-02 07:08 UTC, ZacSweers requested changes
Added a comment for a possible issue (requesting changes on that).

Thinking more, the reflective bit for getting the annotations makes sense, but it's also not ideal since it breaks proguard and also has reflection cost. One idea is to create a proxy of the target annotation, but maybe that's out of scope for this RFC. What do you think?

An example of what I'm thinking: https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/Types.java#L173-L203

2017-07-02 07:08 UTC, hzsweers commented on auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java
> +            .typeArguments.get(0);
Does this assume there's only one type parameter?

2017-07-02 07:56 UTC, thatJavaNerd commented on auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java
> +            .typeArguments.get(0);
That is correct. The idea was just to introduce the feature, so right now a property with the type `Map<T, U>` will not work as intended.

2017-07-02 08:13 UTC, thatJavaNerd commented
Do we have a rough estimate on how much faster it'll be? If it's just a matter of a few nanoseconds I wouldn't worry about it. On the other hand, we should consider the extreme of a data class with 1000's of properties (however unrealistic that is).

Conceptually, it sounds like a very good idea. It does seem like it'll increase the complexity/readability of the generated code. If it gets implemented it definitely deserves its own PR.

2017-07-03 22:05 UTC, hzsweers commented on auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java
> +            .typeArguments.get(0);
yeah if you wouldn't mind. I don't think we want to only have partial support, and I think it should be doable to just match on all the type arguments

2017-07-03 22:07 UTC, hzsweers commented
So speed isn't really the main bit for me, rather that what this library offers is actually a route to escape needing to do custom rules for reflection. Agreed that should be a separate change though, since we have existing adapter code already anyway doing this

2017-08-13 03:06 UTC, mattbdean commented
Basically what I've done in this last commit is modified the `makeType` method so that it will work with generic types as well. Since `makeType` was already capable of using the Types class for complex types like `List<Map<String, List<Integer>>>`, generic types should now be fully supported with this PR. In other words, we can now do something like this:

```java
@AutoValue
public abstract class Foo<T, U> {
    public abstract Map<U, T> bar();
    public abstract List<T> baz();
    public abstract U qux();

    // <adapter factory method>
}
```

2017-08-18 09:09 UTC, hzsweers commented
This looks reasonable to me. @rharter do you want to take a look too?

2017-08-18 09:09 UTC, ZacSweers approved these changes

2017-08-18 14:37 UTC, rharter commented
This looks good to me.

It looks like users are going to need to put `@Keep` annotations on their simple generic types or add rules if they use proguard, since those are fetched by name.  I'm not sure of the best way to handle that, perhaps just a note in the readme?

2017-08-18 14:37 UTC, rharter approved these changes

2017-08-22 01:19 UTC, mattbdean commented
Is there anything else we need to do before this gets merged?

2017-08-22 02:15 UTC, hzsweers commented
Oops just saw Ryan's comment! I think just a note in the README should suffice. We could explore possibly adding them ourselves if they're present, but worth a separate PR I think and possibly avoidable if we used something like `AutoAnnotation`

2017-08-22 02:15 UTC, merged

2017-08-22 02:15 UTC, hzsweers commented
Thanks @mattbdean!